baseurl                  = "https://www.fetzu.ch/"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "fetzu dot ch: palace of the meh"
theme                    = ["hugo-cloak-email", "sam"]
pygmentsStyle            = "friendly"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"
enableGitInfo = true

[params]
    dateform             = "Mon 02 Jan, 2006"
    dateformshort        = "02 Jan"
    dateformFooter       = "02 Jan 2006"
    dateformfull         = "Mon 2 Jan 2006 15:04:05"
    favicon              = "favicon.ico"
    homepage             = "home"                           # What to call the home page link, link will not be rendered if empty
    footerCopyright      = '&#183; <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a>'

# Metadata for Open Graph and Twitter
    description          = "Julien 'fetzu' Bono's other website."               # Max 160 characters show in search results
    #images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "fetzu dot ch"
    # rss                = ""

[[params.videoBackground.sources]]
    #source  = "/static/bg-videos"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "blog"
    text = "blog"

[[params.mainMenu]]
    link = "https://console.fetzu.ch/"
    text = "console"

[[params.mainMenu]]
    link = "portfolio"
    text = "portfolio"

[[params.mainMenu]]
    link = "about"
    text = "who is fetzu?"

[imaging]
    quality = 75

[author]
    name = "Julien 'fetzu' Bono"

[frontmatter]
  date = ['date', 'publishdate', 'lastmod', 'modified']
  lastmod = [':git', 'lastmod', 'modified', 'date']

[outputFormats]
  [outputFormats.Sitemap]
    mediatype = "application/xml"
    baseName = "sitemap"

[outputs]
    home = ["HTML", "RSS", "Sitemap"]
    section = ["HTML", "Sitemap"]
    taxonomy = ["HTML", "Sitemap"]
    term = ["HTML"]
