name: Update content

on:
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          token: ${{ secrets.DEPLOYTOKEN }}
            
      - name: Pull & update content submodule recursively
        run: |
          git submodule update --init --remote content

      - name: Commit updates for content submodule
        run: |
          git config user.name "Content Manager"
          git add --all
          git commit -m "chore: Updated content" || echo "No changes to commit"
          git push
